### PR TITLE
Loading file via s3 doubling folder

### PR DESCRIPTION
**Pull request by synbot**
## Description

Unable to load files via s3.  Uploading is fine.
## Details
- Credentials: {{username / password (remove if not applicable)}}
- URL: {{url where problem occurs, remove if not applicable}}
- Note: {{relevant information like related issues, remove if not applicable}}
- Console Error: {{expand and copy from the console (include line error too), remove if not applicable}}

### CODE REVIEW

**Comment by baohx2000** [comment]
:arrow_double_up: :sunny:

**Comment by baohx2000** [comment]
:star: :m:

**Comment by bobeagan** [comment]
:pray:

**Comment by baohx2000** [comment]
:+1:

**Pull request merged**
